### PR TITLE
Kd/improve solver

### PR DESCRIPTION
**Pull request by kdomino**

### CODE REVIEW

**Comment by lpawela** [comment]
Please fix test coverage.

**Comment by kdomino** [comment]
I have removed many tested functions (with tests), hence the coverage has fallen. I have added some new tests in contractions. Nevertheless there is no tests in cuda, detailed_mps, and some tested are needed in utils. I am not qualified there

**Comment by lpawela** [comment]
What is the purpose of `detaied_mps`? Other files you mentioned have no effect on the coverage change as their coverage didn't change.

**Comment by kdomino** [comment]
I see now, you asked to store somewhere the old (my) mps implementation. I did not noticed it has an impact to the coveralls. Where shall I move it, benchamrks?

**Comment by kdomino** [comment]
Or remove from repo?

**Comment by bartekGardas** [comment]
As far as I remebmer this implementation has a slightly different idea than ours, I would store it in someplace.

**Comment by kdomino** [comment]
done

**Review by lpawela — APPROVED** [review]

**Pull request merged**
