### PR TITLE
Allow indexing arrays with states

### PR DESCRIPTION
**Pull request by lpawela**
This allows us to index arrays with states, eg
```julia
σ = (1, -1, -1, 1, 1)
d = 2^length(σ)
x = rand(2, 2, d)
@state x[1, 1, σ] # == x[1, 1, 20]
```

### CODE REVIEW

**Comment by kdomino** [comment]
But how does it comply with the (low) energy spectrum, where we can not map: (-1, .., -1,  -1) -> 1, (-1, .., -1,  1) -> 2 etc ...

**Comment by bartekGardas** [comment]
I do not understand @kdomino objection. Can you please elaborate a bit more? The 1-1 mapping do exist, and hence it can be used to establish "state numbering".

**Comment by kdomino** [comment]
In the low energy spectrum you sort states by energies, hence indexing is energy dependent this is mode 5, am I right? 
In modes 1-4 you may number (sub)states as you wish, i.e. either using subspace of the energy spectrum or simple mapping (-1, .., -1,-1) -> 1; (-1, ..., -1, 1)  -> etc ....   Nevertheless It must be consistent, i.e. in PEPS building and in setting particular index value.

**Comment by kdomino** [comment]
Mom working example is in kd/indexing-tests, benchmarks/indexing_example.jl

**Comment by kdomino** [comment]
Non working example is in branch kd/indexing-tests   benchmarks/indexing_example.jl

**Comment by kdomino** [comment]
https://github.com/iitis/SpinGlassPEPS.jl/tree/kd/indexing-tests/benchmarks

**Comment by bartekGardas** [comment]
update_cells!(
  g_ising,
  rule = square_lattice((m, 1, n, 1, t)),
)

**Comment by bartekGardas** [comment]
It should work for now. Let's add some examples, especially for comparison with the Gibbs state.

**Review by bartekGardas — APPROVED** [review]
Let's merge as is, it should work for now.

**Pull request merged**
