### PR TITLE
Allow arbitrary number of states for each cluster

### PR DESCRIPTION
**Pull request by lpawela**

### CODE REVIEW

**Review by bartekGardas — COMMENTED** [review]
Can we add an example showing how this works when you have clusters of different sizes (like in Krzysiek's examples)?

**Comment by bartekGardas** [comment]
How would I use this on the example from here https://github.com/iitis/SpinGlassPEPS.jl/blob/sasina/test/indexing.jl?

**Comment by lpawela** [comment]
You can change the line
```julia
fg_bf = factor_graph(
    ig,
    energy=energy,
    spectrum= x -> brute_force(x, num_states=2),
)
```
to 
```julia
fg_bf = factor_graph(
    ig,
    2
    energy=energy,
    spectrum= x -> brute_force(x),
)
```
If you had a more complicated example you could specify the number of states for each cluster
```julia
fg_bf = factor_graph(
    ig,
    Dict(1=>2, 2=>1),
    energy=energy,
    spectrum=brute_force,
)
```
which means the first cluster should have two states, and the second one only a single one. If you omit a cluster `cl`, its `cl.rank` is taken as the number of states.

**Comment by bartekGardas** [comment]
This is nice. Q: num_states=2 is redundant in the last example, is it? 
I'have tried this on a simple example, and it does not work, cf.
https://github.com/iitis/SpinGlassPEPS.jl/blob/sasina/test/indexing.jl

**Comment by lpawela** [comment]
I corrected the last example. Did you merge this branch into `sasina`? If not, how can it work :)?

**Comment by bartekGardas** [comment]
Yes, I did. This example does not work on your branch either :-)

**Comment by lpawela** [comment]
The example as is provided should fail - `num_states > prod(cl.rank)`. I added a fallback, if `num_states` is set by the user as greater than the rank of the cluster, we set `num_states = rank`.

**Comment by bartekGardas** [comment]
This is not true. The first cluster -- A1 has 2 spins, and thus num_states=4 should work, the second one -- A2 has only 1 spin, and num_states=2 should work as well. In this example, one should be able, therefore, to specify Dict(1=>4, 2=>2). But this does not work.

**Comment by lpawela** [comment]
The rank is taken from the cluster constructed in `factor_graph`. Upon inspection in fact we get `prod(cl.rank)` equal to either `1` or `2`.
Are you sure that in this example we don't have trivial systems?

**Comment by bartekGardas** [comment]
OK, I see now what the problem was -- lack of `update_cells!` after reading the instance. Now it works, sort of, since both `full_spectrum`, and `full_spectrum` return the spectrum in the same order, which is really, really suspicion!  I believe, this goes directly to the Krzysiek's problems with projectors. You can easily see this by running the example.

**Comment by lpawela** [comment]
This is a problem with the instance itself - the ordering just happens to be the same.
I think we should merge this now.

**Comment by bartekGardas** [comment]
I agree.

**Review by bartekGardas — APPROVED** [review]
OK.

**Pull request merged**
